PRODUCT_READ_HISTORY_TABLE = 'product_read_history'
PRODUCT_READ_CHANGES_TABLE = 'product_read_changes'
ASIN_FIELD = 'asin'
IMAGE_VARIATIONS_FIELD = 'image_variations'
READ_TIME_FIELD = 'read_time'
LISTING_PRICE_FIELD = 'listing_price'
IS_ACTIVE_FIELD = 'is_active'
MERCHANT_FIELD = 'merchant'

AB_TEST_RUNS_TABLE = 'ab_test_runs'
AB_TEST_ID_FIELD = 'test_id'
RUN_ID_FIELD = 'run_id'
RUN_TIME_FIELD = 'run_time'
FEED_ID_FIELD = 'feed_id'
VARIATION_FIELD = 'variation'

MERCHANTS_TABLE = 'merchants'
MERCHANT_ID_FIELD = 'merchant_id'
# Generated by Registering a new Developer App - https://developer-docs.amazon.com/amazon-shipping/docs/registering-as-a-developer
# Click "View" under LWA credentials
LWA_APP_ID_FIELD = 'lwa_app_id'
# Generated by Registering a new Developer App - https://developer-docs.amazon.com/amazon-shipping/docs/registering-as-a-developer
# Click "View" under LWA credentials
LWA_CLIENT_SECRET_FIELD = 'lwa_client_secret'
# Generated by creating new access key in the IAM panel in AWS
SP_API_SECRET_KEY_FIELD = 'sp_api_secret_key'
# Generated in IAM panel AWS
# ARN of the authorized user
# Need to add role and policy - https://developer-docs.amazon.com/amazon-shipping/docs/creating-and-configuring-iam-policies-and-entities
SP_API_ROLE_ARN_FIELD = 'sp_api_role_arn'
# Generated by Self authorize flow - https://developer-docs.amazon.com/amazon-shipping/docs/self-authorization
# Look for the arrow next to Edit App
# Leading to a URL that looks like https://sellercentral.amazon.com/sellingpartner/self-authorize/amzn1.sp.solution....
SP_API_REFRESH_TOKEN_FIELD = 'sp_api_refresh_token'
# Generated by creating new access key in the IAM panel in AWS
SP_API_ACCESS_KEY_FIELD = 'sp_api_access_key'
