IMAGES_HISTORY_TABLE = 'product_images_history'
IMAGES_CHANGES_TABLE = 'images_changes'
ASIN_FIELD = 'asin'
IMAGE_VARIATIONS_FIELD = 'image_variations'
READ_TIME_FIELD = 'read_time'
USER_ID_FIELD = 'user_id'

AB_TEST_RUNS_TABLE = 'ab_test_runs'
AB_TEST_ID_FIELD = 'test_id'
RUN_ID_FIELD = 'run_id'
RUN_TIME_FIELD = 'run_time'
FEED_ID_FIELD = 'feed_id'
VARIATION_FIELD = 'variation'
