PRODUCT_READ_HISTORY_TABLE = 'product_read_history'
PRODUCT_READ_CHANGES_TABLE = 'product_read_changes'
ASIN_FIELD = 'asin'
IMAGE_VARIATIONS_FIELD = 'image_variations'
READ_TIME_FIELD = 'read_time'
LISTING_PRICE_FIELD = 'listing_price'
MERCHANT_FIELD = 'merchant'

AB_TEST_RUNS_TABLE = 'ab_test_runs'
AB_TEST_ID_FIELD = 'test_id'
RUN_ID_FIELD = 'run_id'
RUN_TIME_FIELD = 'run_time'
FEED_ID_FIELD = 'feed_id'
VARIATION_FIELD = 'variation'

MERCHANTS_TABLE = 'merchants'
MERCHANT_ID_FIELD = 'user_id'
LWA_APP_ID_FIELD = 'lwa_app_id'
LWA_CLIENT_SECRET_FIELD = 'lwa_client_secret'
