START_DATE_FIELD = 'Start date'
END_DATE_FIELD = 'End date'
ROTATION_FIELD = 'Rotation (hour)'
FLATFILE_FIELD = {'A': 'Flatfile A', 'B': 'Flatfile B'}
STATUS_FIELD = 'Status'
TEST_ID_FIELD = 'test_id'
MERCHANT_FIELD = 'Merchant'

PYTHON_DATETIME_FORMAT = '%Y-%m-%d %H:%M'
PYTHON_DATETIME_TIMEZONE_FORMAT = f'{PYTHON_DATETIME_FORMAT} %z'
AIRTABLE_DATETIME_FORMAT = '%Y-%m-%d'
AIRTABLE_DATETIME_TIMEZONE_FORMAT = f'{AIRTABLE_DATETIME_FORMAT} %z'
AMAZON_TIMEZONE_NAME = 'US/Pacific'  # PDT timezone

FLATFILE_SHEET_NAME = 'Template'
FLATFILE_ASIN_COLUMN = 'Product ID'
